# configuration for "master" branch
-
  branches:
    only:
      - master
  environment:
    apiKey:
      secure: 2ZZXSRRBupkaRGRnD1zefkkjmURoXN+QzdeutbdwckTXmmPpe7jmr6HQpgm0R2C4
  version: 0.4.0.{build}
  nuget:
    disable_publish_on_pr: true
  test: off
  build_script:
  - build.bat NEdifis.sln /t:CoverageReport /v:m
  after_build:
  - ps: >-
      $wc = New-Object 'System.Net.WebClient'
    
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresults\NEdifis.Tests.xml))


      
  before_deploy:
  - nuget setapikey %apiKey% -Verbosity quiet
  deploy_script:
  - build.bat NEdifis.sln /t:Deploy /v:m

# "fall back" configuration for all other branches
- 
  version: 0.4.0.{build}
  test: off
  deploy: off
  nuget:
    disable_publish_on_pr: true
  build_script:
  - build.bat NEdifis.sln /t:CoverageReport /v:m
  